name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.10.2
  widgetbook_annotation: ^3.2.0
  horizon:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.9.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
